spring.application.name=grab-gia-su-backend

server.port=8080

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=grab_gia_su;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:yourStrong(!)Password}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

security.jwt.secret-key=${JWT_SECRET_KEY:QmFzZTY0U2VjcmV0S2V5Rm9yR3JhYkdpYVN1QmFja2VuZDIwMjY=}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
